import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Box from "@mui/material/Box";
import { useRouter } from "next/router";
import { Button, TextField } from "@mui/material";

const Home: NextPage = () => {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <h1 className={styles.title}>
          Welcome to <a href="">Web3 Newbie</a>
        </h1>

        <Box
          display="flex"
          alignItems="center"
          gap="20px"
          sx={{ marginTop: 2, width: 500 }}
        >
          <TextField
            id="outlined-basic"
            placeholder={"请输入 NFT 合约地址"}
            label=""
            variant="outlined"
            fullWidth={true}
          />
          <Button
            variant="contained"
            sx={{ width: 120 }}
            onClick={() => {
              router.push(`/group/0x2E742dbC8d79318013eF9eF89381274147c52f34`);
            }}
          >
            点击跳转
          </Button>
        </Box>
      </main>

      <footer className={styles.footer}>
        <a href="https://lxdao.io" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by web3 women newbie
        </a>
      </footer>
    </div>
  );
};

export default Home;
